<div class="module">
    <div class="span3">
		<form action="?" id="login-form" method="POST">
			<div class="item">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" placeholder="jsmith" />
            </div>
			<div class="item">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" placeholder="********" />
            </div>
			<div class="item">
                <input type="submit" id="submit" name="submit" class="button" value="Log in" />
            </div>
		</form>
	</div>
</div>