</div>
    </div>

    <footer>
        <div id="copyright">
            SwiftIDE &copy; 2013. All rights are reserved.
        </div>

        <nav>
            <ul>
                <li><a href="terms.html">Terms</a></li>
                <li><a href="privacy.html">Privacy</a></li>
                <li><a href="contact.html">Contact</a></li>
            </ul>
        </nav>
    </footer>

    <!-- <script src="js/" type="text/javascript"></script> -->
</body>
</html>
