<div class="module">
    <div class="span2">
        <iframe width="624" height="468" src="http://www.youtube.com/embed/iGKpHEkCIjU" frameborder="0" allowfullscreen></iframe>
    </div>
    <div class="span1">
        <form accept-charset="UTF-8" id="login-form" action="auth.php" autocomplete="off" class="member-signin" method="post">
        	<div class="item">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" placeholder="jsmith" />
            </div>
            <div class="item">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" placeholder="********" />
            </div>
            <div class="item">
                <input type="submit" id="submit" name="submit" class="button" value="Log in" />
            </div>
        </form>
    </div>
</div>

<div class="module">
    <h2>Featured Project</h2>
    <div class="span2">
        <img src="media/images/feature.png" alt="" width="624" height="326" />
    </div>
	<div class="span1">
        <h3>Forget Me Not!</h3>

        <p>
        	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed semper, libero vel posuere consectetur, ipsum risus
        	imperdiet justo, pulvinar pellentesque velit nisi sed ligula. Integer posuere interdum ante, vel facilisis neque
            lacinia malesuada. Donec ut orci scelerisque, auctor risus sit amet, semper eros. Duis nec nisl pharetra, laoreet
            nulla tincidunt, scelerisque risus. Sed nunc leo, tempus eu placerat vitae, malesuada a elit.
        </p>

        <a href="#" class="button">View Project</a>
    </div>
</div>