<div class="module">
    <div class="span3">

        <form action="?" class="signup-form" method="post">
            <div class="item">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" placeholder="jsmith" />
            </div>

            <div class="item">
                <label for="email">Email:</label>
                <input type="text" id="email" name="email" placeholder="jsmith@someone.com" />
            </div>

            <div class="item">
                <label for="first_name">First Name:</label>
                <input type="text" id="first_name" name="first_name" placeholder="john" />
            </div>

            <div class="item">
                <label for="last_name">Last Name:</label>
                <input type="text" id="last_name" name="last_name" placeholder="Smith" />
            </div>

            <div class="item">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" placeholder="********" />
            </div>

            <div class="item">
                <p>
                    By clicking "Sign up", you agree to our <a href="terms.html" class="active">terms of service</a> and <a href="privacy.html" class="active">privacy policy</a>.
                </p>
            </div>

            <div class="item">
                <input type="submit" id="submit" name="submit" class="button" value="Create an account" />
            </div>
        </form>

    </div>
</div>